name: Blender Build (Windows)

on: push

env:
  lib_dir: C:\blender-build/lib
  tag_name: blender-3.6-release
  branch_name: goo-engine-v3.6-release

# For release create
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
      with:
        fetch-depth: 0
    - name: Create working folders
      run: |
        mkdir ${{ env.lib_dir }}
        New-Item -ItemType SymbolicLink -Path "../lib" -Target "${{ env.lib_dir }}"
        $cmdOutput = Split-Path -Path $pwd -Leaf
        $_ver = "$(git rev-list HEAD --count)-$(git rev-parse --short=8 HEAD)"
        echo "commit_ver=${{ env.branch_name }}-$_ver" >> "$Env:GITHUB_ENV"
        echo "arc_name=${{ env.branch_name }}-$_ver.7z" >> "$Env:GITHUB_ENV"
    - name: Cache Precompiled Dependencies
      id: cache-svn-dep
      uses: actions/cache@main
      with:
        path: ${{ env.lib_dir }}
        key: ${{ runner.os }}--${{ env.tag_name }}
    - name: Install python dependencies
      run: pip install -r requirements.txt
    - name: Checkout Precompiled Dependencies
      if: false
      working-directory: ${{ env.lib_dir }}
      run: svn checkout https://svn.blender.org/svnroot/bf-blender/tags/${{ env.tag_name }}/lib/win64_vc15
    - name: Update dependencies
      run: ./make.bat update
    - name: Build Blender
      run: ./make.bat
    - name: Zip Release
      run: 7z a -m0=LZMA2 -mx9 ${{ github.workspace }}/${{ env.arc_name }} ../build_windows_x64_vc17_Release/bin/Release

    - name: Upload Artifact
      uses: actions/upload-artifact@main
      if: false
      with:
        name: ${{ env.arc_name }}
        path: ${{ github.workspace }}/${{ env.arc_name }}

    - name: Create Blender Release
      if: false
      working-directory: ${{ env.build_dir }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create "${{ env.commit_ver }}" ${{ github.workspace }}/${{ env.arc_name }} --target ${{ GITHUB.SHA }} -t "${{ env.commit_ver }}"
